# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d751e7919c30824434496c4110db0c2928d6110e6f1ce6a70cfbb170a7d1a31edda54797a0e87e8353c2b76a146a5ed87d7187745d11ca8cbee1f9fc0d44925

test:
  secret_key_base: fc98d68cdf47108a9132b49ec5be5bfbb631a0ec23665486a129b4c18d417a64943a2711e97d6191d2cb2be5f6f33c106e58a69498e4a299095c79378e84038c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
